liip_imagine:
    filter_sets: 
        thumb:
            quality: 75
            filters:
               thumbnail:
                    size:       [360, 230]
                    mode:        outbound
        medium:
            quality: 75
            filters:
               thumbnail:
                    size:       [700, 530]
                    mode:        outbound